/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package clinet;
import core.*;
/**
 *
 * @author Ansam
 */
public class Compare extends javax.swing.JFrame {

    /**
     * Creates new form Compare
     */
    public Compare(Item item1,Item item2) {
        initComponents();
         ItemName.setText(item1.Name);
         ItemName1.setText(item2.Name);
        ItemDesc.setText(item1.Descritption);
         ItemDesc2.setText(item2.Descritption);
        ItemCatogery1.setText(item1.Category);
         ItemCatogery2.setText(item2.Category);
        ItemPrice.setText("" + item1.Price);
        ItemPrice1.setText("" + item2.Price);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        Name = new javax.swing.JLabel();
        ItemDesc = new javax.swing.JLabel();
        ItemName = new javax.swing.JLabel();
        Price = new javax.swing.JLabel();
        ItemPrice = new javax.swing.JLabel();
        Catogery1 = new javax.swing.JLabel();
        ItemCatogery1 = new javax.swing.JLabel();
        Catogery2 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        Name1 = new javax.swing.JLabel();
        ItemDesc2 = new javax.swing.JLabel();
        ItemName1 = new javax.swing.JLabel();
        Price1 = new javax.swing.JLabel();
        ItemPrice1 = new javax.swing.JLabel();
        Catogery3 = new javax.swing.JLabel();
        ItemCatogery2 = new javax.swing.JLabel();
        Catogery4 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);

        jPanel3.setBackground(new java.awt.Color(0, 51, 102));
        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 3));
        jPanel3.setForeground(new java.awt.Color(255, 255, 255));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Name.setFont(new java.awt.Font("Agency FB", 0, 24)); // NOI18N
        Name.setForeground(new java.awt.Color(255, 255, 255));
        Name.setText("Name :");
        jPanel3.add(Name, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 120, 60, 30));

        ItemDesc.setFont(new java.awt.Font("Agency FB", 0, 24)); // NOI18N
        ItemDesc.setForeground(new java.awt.Color(255, 255, 255));
        ItemDesc.setText("jLabel11");
        jPanel3.add(ItemDesc, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 260, -1, -1));

        ItemName.setFont(new java.awt.Font("Agency FB", 0, 24)); // NOI18N
        ItemName.setForeground(new java.awt.Color(255, 255, 255));
        ItemName.setText("jLabel11");
        jPanel3.add(ItemName, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 120, -1, -1));

        Price.setFont(new java.awt.Font("Agency FB", 0, 24)); // NOI18N
        Price.setForeground(new java.awt.Color(255, 255, 255));
        Price.setText("Price :");
        jPanel3.add(Price, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 170, 50, 30));

        ItemPrice.setFont(new java.awt.Font("Agency FB", 0, 24)); // NOI18N
        ItemPrice.setForeground(new java.awt.Color(255, 255, 255));
        ItemPrice.setText("jLabel11");
        jPanel3.add(ItemPrice, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 170, -1, -1));

        Catogery1.setFont(new java.awt.Font("Agency FB", 0, 24)); // NOI18N
        Catogery1.setForeground(new java.awt.Color(255, 255, 255));
        Catogery1.setText("Catogery :");
        jPanel3.add(Catogery1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 210, 80, 30));

        ItemCatogery1.setFont(new java.awt.Font("Agency FB", 0, 24)); // NOI18N
        ItemCatogery1.setForeground(new java.awt.Color(255, 255, 255));
        ItemCatogery1.setText("jLabel11");
        jPanel3.add(ItemCatogery1, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 210, -1, -1));

        Catogery2.setFont(new java.awt.Font("Agency FB", 0, 24)); // NOI18N
        Catogery2.setForeground(new java.awt.Color(255, 255, 255));
        Catogery2.setText("Description :");
        jPanel3.add(Catogery2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 260, 100, 30));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/1492585871_product-sales-report.png"))); // NOI18N
        jPanel3.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, -1, -1));

        jPanel1.setBackground(new java.awt.Color(0, 51, 102));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 3));

        Name1.setFont(new java.awt.Font("Agency FB", 0, 24)); // NOI18N
        Name1.setForeground(new java.awt.Color(255, 255, 255));
        Name1.setText("Name :");

        ItemDesc2.setFont(new java.awt.Font("Agency FB", 0, 24)); // NOI18N
        ItemDesc2.setForeground(new java.awt.Color(255, 255, 255));
        ItemDesc2.setText("jLabel11");

        ItemName1.setFont(new java.awt.Font("Agency FB", 0, 24)); // NOI18N
        ItemName1.setForeground(new java.awt.Color(255, 255, 255));
        ItemName1.setText("jLabel11");

        Price1.setFont(new java.awt.Font("Agency FB", 0, 24)); // NOI18N
        Price1.setForeground(new java.awt.Color(255, 255, 255));
        Price1.setText("Price :");

        ItemPrice1.setFont(new java.awt.Font("Agency FB", 0, 24)); // NOI18N
        ItemPrice1.setForeground(new java.awt.Color(255, 255, 255));
        ItemPrice1.setText("jLabel11");

        Catogery3.setFont(new java.awt.Font("Agency FB", 0, 24)); // NOI18N
        Catogery3.setForeground(new java.awt.Color(255, 255, 255));
        Catogery3.setText("Catogery :");

        ItemCatogery2.setFont(new java.awt.Font("Agency FB", 0, 24)); // NOI18N
        ItemCatogery2.setForeground(new java.awt.Color(255, 255, 255));
        ItemCatogery2.setText("jLabel11");

        Catogery4.setFont(new java.awt.Font("Agency FB", 0, 24)); // NOI18N
        Catogery4.setForeground(new java.awt.Color(255, 255, 255));
        Catogery4.setText("Description :");

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/1492585871_product-sales-report.png"))); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(Name1, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(160, 160, 160)
                        .addComponent(ItemName1))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(Price1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(170, 170, 170)
                        .addComponent(ItemPrice1))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(Catogery3, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(140, 140, 140)
                        .addComponent(ItemCatogery2))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(Catogery4, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(120, 120, 120)
                        .addComponent(ItemDesc2)))
                .addContainerGap(24, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(jLabel1)
                .addGap(26, 26, 26)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Name1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ItemName1))
                .addGap(20, 20, 20)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Price1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ItemPrice1))
                .addGap(10, 10, 10)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Catogery3, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ItemCatogery2))
                .addGap(20, 20, 20)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Catogery4, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ItemDesc2))
                .addContainerGap(161, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 308, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
 

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Catogery1;
    private javax.swing.JLabel Catogery2;
    private javax.swing.JLabel Catogery3;
    private javax.swing.JLabel Catogery4;
    private javax.swing.JLabel ItemCatogery1;
    private javax.swing.JLabel ItemCatogery2;
    private javax.swing.JLabel ItemDesc;
    private javax.swing.JLabel ItemDesc2;
    private javax.swing.JLabel ItemName;
    private javax.swing.JLabel ItemName1;
    private javax.swing.JLabel ItemPrice;
    private javax.swing.JLabel ItemPrice1;
    private javax.swing.JLabel Name;
    private javax.swing.JLabel Name1;
    private javax.swing.JLabel Price;
    private javax.swing.JLabel Price1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    // End of variables declaration//GEN-END:variables
}
