/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package clinet;

import java.util.ArrayList;
import java.util.Vector;
import core.*;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.Icon;

/**
 *
 * @author Ansam
 */
public class ItemDetails extends javax.swing.JFrame {

    /**
     * Creates new form ItemDetails
     */
    ArrayList<User> Session;
    ConnectDB connection;
    public ArrayList details = new ArrayList();
    public Item i = new Item();

    public ItemDetails(ArrayList<Vector> d,ArrayList<User> Session,ConnectDB con) throws SQLException {
        initComponents();
        connection=con;
        this.Session=Session;
         
        int ID = Integer.parseInt(d.get(0).get(0).toString());
        
        i.itemDetails(ID,connection);
        ItemDesc.setText(i.Descritption);
        ItemCatogery1.setText(i.Category);
        ItemName.setText(i.Name);
        ItemPrice.setText("" + i.Price);
        
        image.setIcon(new javax.swing.ImageIcon(i.PhotoURL));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        Name = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        Catogery = new javax.swing.JLabel();
        ItemDesc = new javax.swing.JLabel();
        ItemName = new javax.swing.JLabel();
        Price = new javax.swing.JLabel();
        ItemPrice = new javax.swing.JLabel();
        Catogery1 = new javax.swing.JLabel();
        ItemCatogery1 = new javax.swing.JLabel();
        Catogery2 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jButton4 = new javax.swing.JButton();
        image = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel3.setBackground(new java.awt.Color(0, 51, 102));
        jPanel3.setForeground(new java.awt.Color(255, 255, 255));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Name.setFont(new java.awt.Font("Agency FB", 0, 24)); // NOI18N
        Name.setForeground(new java.awt.Color(255, 255, 255));
        Name.setText("Name :");
        jPanel3.add(Name, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 120, 60, 30));

        jButton3.setBackground(new java.awt.Color(255, 204, 153));
        jButton3.setFont(new java.awt.Font("Agency FB", 0, 18)); // NOI18N
        jButton3.setText("Compare");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 300, 120, 40));

        Catogery.setFont(new java.awt.Font("Agency FB", 0, 24)); // NOI18N
        Catogery.setForeground(new java.awt.Color(255, 255, 255));
        Catogery.setText("Compare with  :");
        jPanel3.add(Catogery, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 310, 120, 30));

        ItemDesc.setFont(new java.awt.Font("Agency FB", 0, 24)); // NOI18N
        ItemDesc.setForeground(new java.awt.Color(255, 255, 255));
        ItemDesc.setText("jLabel11");
        jPanel3.add(ItemDesc, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 260, -1, -1));

        ItemName.setFont(new java.awt.Font("Agency FB", 0, 24)); // NOI18N
        ItemName.setForeground(new java.awt.Color(255, 255, 255));
        ItemName.setText("jLabel11");
        jPanel3.add(ItemName, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 120, -1, -1));

        Price.setFont(new java.awt.Font("Agency FB", 0, 24)); // NOI18N
        Price.setForeground(new java.awt.Color(255, 255, 255));
        Price.setText("Price :");
        jPanel3.add(Price, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 170, 50, 30));

        ItemPrice.setFont(new java.awt.Font("Agency FB", 0, 24)); // NOI18N
        ItemPrice.setForeground(new java.awt.Color(255, 255, 255));
        ItemPrice.setText("jLabel11");
        jPanel3.add(ItemPrice, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 170, -1, -1));

        Catogery1.setFont(new java.awt.Font("Agency FB", 0, 24)); // NOI18N
        Catogery1.setForeground(new java.awt.Color(255, 255, 255));
        Catogery1.setText("Catogery :");
        jPanel3.add(Catogery1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 210, 80, 30));

        ItemCatogery1.setFont(new java.awt.Font("Agency FB", 0, 24)); // NOI18N
        ItemCatogery1.setForeground(new java.awt.Color(255, 255, 255));
        ItemCatogery1.setText("jLabel11");
        jPanel3.add(ItemCatogery1, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 210, -1, -1));

        Catogery2.setFont(new java.awt.Font("Agency FB", 0, 24)); // NOI18N
        Catogery2.setForeground(new java.awt.Color(255, 255, 255));
        Catogery2.setText("Description :");
        jPanel3.add(Catogery2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 260, 100, 30));

        jTextField2.setBackground(new java.awt.Color(255, 204, 153));
        jTextField2.setText("Title");
        jPanel3.add(jTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 300, 130, 30));

        jButton4.setBackground(new java.awt.Color(255, 204, 153));
        jButton4.setFont(new java.awt.Font("Agency FB", 0, 18)); // NOI18N
        jButton4.setText("Add to cart");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 380, 120, 40));

        image.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/1492585871_product-sales-report.png"))); // NOI18N
        jPanel3.add(image, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, -1, -1));

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 570, 450));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        String name= jTextField2.getText();
        Item i1= new Item();
        try {
           
            ArrayList<Item> iL= new ArrayList<>();
            iL= i1.SearchByName(name,connection);
           
             new Compare(i,iL.get(0)).setVisible(true);
        } catch (SQLException ex) {
            Logger.getLogger(ShowItems.class.getName()).log(Level.SEVERE, null, ex);
        }

       
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        int CartID= Session.get(0).CartID;
        core.Cart c=new core.Cart();
        c.AddToCart(CartID, i.ID, 1, connection);
        this.dispose();
        
    }//GEN-LAST:event_jButton4ActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Catogery;
    private javax.swing.JLabel Catogery1;
    private javax.swing.JLabel Catogery2;
    private javax.swing.JLabel ItemCatogery1;
    private javax.swing.JLabel ItemDesc;
    private javax.swing.JLabel ItemName;
    private javax.swing.JLabel ItemPrice;
    private javax.swing.JLabel Name;
    private javax.swing.JLabel Price;
    private javax.swing.JLabel image;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JTextField jTextField2;
    // End of variables declaration//GEN-END:variables
}
