package Person;

import clinet.ShowItems;
import core.ConnectDB;
import core.Item;
import core.User;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author Ansam
 */
public class Login extends javax.swing.JFrame {

    /**
     * Creates new form Login
     */
    public static ArrayList<User> Session = new ArrayList<>();
    ConnectDB connection;

    public Login(ConnectDB con) {
        initComponents();
        this.connection = con;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField1 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTextField1.setBackground(new java.awt.Color(255, 204, 153));
        jTextField1.setText("Password");
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 510, 130, 30));

        jLabel3.setFont(new java.awt.Font("Agency FB", 0, 24)); // NOI18N
        jLabel3.setText("Email :");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 470, 50, 30));

        jLabel4.setFont(new java.awt.Font("Agency FB", 0, 24)); // NOI18N
        jLabel4.setText("Password :");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 510, 90, 30));

        jTextField2.setBackground(new java.awt.Color(255, 204, 153));
        jTextField2.setText("Email");
        getContentPane().add(jTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 470, 130, 30));

        jButton1.setBackground(new java.awt.Color(0, 153, 255));
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("LOGIN");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 560, 80, 30));
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 600));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/online-shopping-background_1284-571.jpg"))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 620, 620));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        String email = jTextField2.getText();
        String password = jTextField1.getText();
        User u = new User();
        try {
            if (u.Login(email, password, connection)) {
                Session.add(u);
                this.dispose();
                if (u.Type.equals("Client")) {
                    ArrayList<Item> IL = new ArrayList<>();
                    new ShowItems(IL, 1, Session, connection).setVisible(true);
                }
                if (u.Type.equals("Admin")) {
                    ArrayList<Item> IL = new ArrayList<>();
                    new Admin.ShowItems(IL, 1, Session, connection).setVisible(true);
                }
                if (u.Type.equals("Analyser")) {
                    ArrayList<Item> IL = new ArrayList<>();
                    new Analyser.ShowItems(IL, 1, Session, connection).setVisible(true);
                }
                if (u.Type.equals("ManagerRepresentative")) {
                    ArrayList<Item> IL = new ArrayList<>();
                    new ManagerRepresintive.ShowItems(IL, 1, Session, connection).setVisible(true);
                }
                if (u.Type.equals("Stocker")) {
                    ArrayList<Item> IL = new ArrayList<>();
                    new Stocker.ShowItems(IL, 1, Session, connection).setVisible(true);
                }

            } else {
                new Login(connection).setVisible(true);
            }
        } catch (SQLException ex) {
            Logger.getLogger(Login.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    // End of variables declaration//GEN-END:variables
}
