/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Stocker;

import Admin.*;

/**
 *
 * @author Ansam
 */
public class AddItem extends javax.swing.JFrame {

    /**
     * Creates new form AddItem
     */
    public AddItem() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel5 = new javax.swing.JPanel();
        Name2 = new javax.swing.JLabel();
        jButton5 = new javax.swing.JButton();
        Price = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jComboBox2 = new javax.swing.JComboBox<>();
        Name3 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        Name4 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        Name5 = new javax.swing.JLabel();
        jTextField4 = new javax.swing.JTextField();
        Name6 = new javax.swing.JLabel();
        jButton6 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);

        jPanel5.setBackground(new java.awt.Color(0, 51, 102));
        jPanel5.setForeground(new java.awt.Color(255, 255, 255));
        jPanel5.setAutoscrolls(true);
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Name2.setFont(new java.awt.Font("Agency FB", 0, 24)); // NOI18N
        Name2.setForeground(new java.awt.Color(255, 255, 255));
        Name2.setText("Description :");
        jPanel5.add(Name2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 330, 120, 30));

        jButton5.setBackground(new java.awt.Color(255, 204, 153));
        jButton5.setFont(new java.awt.Font("Agency FB", 0, 18)); // NOI18N
        jButton5.setText("Save");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jPanel5.add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 560, 120, 40));

        Price.setFont(new java.awt.Font("Agency FB", 0, 24)); // NOI18N
        Price.setForeground(new java.awt.Color(255, 255, 255));
        Price.setText("Category :");
        jPanel5.add(Price, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, 100, 30));

        jTextField2.setBackground(new java.awt.Color(255, 204, 153));
        jTextField2.setText("Number");
        jPanel5.add(jTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 180, 130, 30));

        jComboBox2.setBackground(new java.awt.Color(255, 204, 153));
        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Clothes", "Food", "Books", " ", " " }));
        jPanel5.add(jComboBox2, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 90, -1, -1));

        Name3.setFont(new java.awt.Font("Agency FB", 0, 24)); // NOI18N
        Name3.setForeground(new java.awt.Color(255, 255, 255));
        Name3.setText("Item Name :");
        jPanel5.add(Name3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, 120, 30));

        jTextField3.setBackground(new java.awt.Color(255, 204, 153));
        jTextField3.setText("Number");
        jPanel5.add(jTextField3, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 30, 130, 30));

        Name4.setFont(new java.awt.Font("Agency FB", 0, 24)); // NOI18N
        Name4.setForeground(new java.awt.Color(255, 255, 255));
        Name4.setText("Quantity :");
        jPanel5.add(Name4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 180, 120, 30));

        jTextArea1.setBackground(new java.awt.Color(255, 204, 153));
        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        jPanel5.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 350, 170, 170));

        Name5.setFont(new java.awt.Font("Agency FB", 0, 24)); // NOI18N
        Name5.setForeground(new java.awt.Color(255, 255, 255));
        Name5.setText("Price :");
        jPanel5.add(Name5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 130, 120, 30));

        jTextField4.setBackground(new java.awt.Color(255, 204, 153));
        jTextField4.setText("Number");
        jPanel5.add(jTextField4, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 130, 130, 30));

        Name6.setFont(new java.awt.Font("Agency FB", 0, 24)); // NOI18N
        Name6.setForeground(new java.awt.Color(255, 255, 255));
        Name6.setText("Photo :");
        jPanel5.add(Name6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 250, 120, 30));

        jButton6.setBackground(new java.awt.Color(255, 204, 153));
        jButton6.setFont(new java.awt.Font("Agency FB", 0, 18)); // NOI18N
        jButton6.setText("Upload");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        jPanel5.add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 250, 70, 30));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, 473, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, 620, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton6ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AddItem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AddItem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AddItem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AddItem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AddItem().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Name2;
    private javax.swing.JLabel Name3;
    private javax.swing.JLabel Name4;
    private javax.swing.JLabel Name5;
    private javax.swing.JLabel Name6;
    private javax.swing.JLabel Price;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    // End of variables declaration//GEN-END:variables
}
