/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Admin;

import core.Admin;
import core.ConnectDB;
import core.User;
import java.util.ArrayList;

/**
 *
 * @author Ansam
 */
public class AddCategory extends javax.swing.JFrame {

    /**
     * Creates new form AddCategory
     */
    ConnectDB connection;
    public AddCategory(ConnectDB con) {
        initComponents();
        connection=con;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel5 = new javax.swing.JPanel();
        Name2 = new javax.swing.JLabel();
        jButton5 = new javax.swing.JButton();
        Name = new javax.swing.JTextField();
        Name3 = new javax.swing.JLabel();
        desc = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);

        jPanel5.setBackground(new java.awt.Color(0, 51, 102));
        jPanel5.setForeground(new java.awt.Color(255, 255, 255));
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Name2.setFont(new java.awt.Font("Agency FB", 0, 24)); // NOI18N
        Name2.setForeground(new java.awt.Color(255, 255, 255));
        Name2.setText("Category Name :");
        jPanel5.add(Name2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, 130, 30));

        jButton5.setBackground(new java.awt.Color(255, 204, 153));
        jButton5.setFont(new java.awt.Font("Agency FB", 0, 18)); // NOI18N
        jButton5.setText("Save");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jPanel5.add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 190, 120, 40));

        Name.setBackground(new java.awt.Color(255, 204, 153));
        Name.setText("Number");
        jPanel5.add(Name, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 30, 130, 30));

        Name3.setFont(new java.awt.Font("Agency FB", 0, 24)); // NOI18N
        Name3.setForeground(new java.awt.Color(255, 255, 255));
        Name3.setText("Category Describtion:");
        jPanel5.add(Name3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, 180, 30));

        desc.setBackground(new java.awt.Color(255, 204, 153));
        desc.setText("Number");
        jPanel5.add(desc, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 90, 180, 90));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, 397, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, 261, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        String name= Name.getText();
        String Desc= desc.getText();
        core.Admin a= new Admin();
        a.AddCategory(name, Desc, connection);
        this.dispose();
    }//GEN-LAST:event_jButton5ActionPerformed

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Name;
    private javax.swing.JLabel Name2;
    private javax.swing.JLabel Name3;
    private javax.swing.JTextField desc;
    private javax.swing.JButton jButton5;
    private javax.swing.JPanel jPanel5;
    // End of variables declaration//GEN-END:variables
}
