/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Admin;

import core.ConnectDB;
import core.Image;
import core.Item;
import java.io.File;
import javax.swing.JComboBox;
import javax.swing.JFileChooser;

/**
 *
 * @author Ansam
 */
public class AddItem extends javax.swing.JFrame {

    /**
     * Creates new form AddItem
     */
    ConnectDB connection;
Image i = new Image();
int select=0;
    public AddItem(ConnectDB con) {
        initComponents();
        connection = con;

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel5 = new javax.swing.JPanel();
        Name2 = new javax.swing.JLabel();
        upload = new javax.swing.JButton();
        Price = new javax.swing.JLabel();
        price1 = new javax.swing.JTextField();
        Category = new javax.swing.JComboBox<>();
        Name3 = new javax.swing.JLabel();
        Name = new javax.swing.JTextField();
        Name4 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        Desc = new javax.swing.JTextArea();
        Name5 = new javax.swing.JLabel();
        jButton6 = new javax.swing.JButton();
        Name6 = new javax.swing.JLabel();
        quantity = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);

        jPanel5.setBackground(new java.awt.Color(0, 51, 102));
        jPanel5.setForeground(new java.awt.Color(255, 255, 255));
        jPanel5.setAutoscrolls(true);
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Name2.setFont(new java.awt.Font("Agency FB", 0, 24)); // NOI18N
        Name2.setForeground(new java.awt.Color(255, 255, 255));
        Name2.setText("Photo :");
        jPanel5.add(Name2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 220, 120, 30));

        upload.setBackground(new java.awt.Color(255, 204, 153));
        upload.setFont(new java.awt.Font("Agency FB", 0, 18)); // NOI18N
        upload.setText("Upload");
        upload.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                uploadActionPerformed(evt);
            }
        });
        jPanel5.add(upload, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 220, 70, 30));

        Price.setFont(new java.awt.Font("Agency FB", 0, 24)); // NOI18N
        Price.setForeground(new java.awt.Color(255, 255, 255));
        Price.setText("Category :");
        jPanel5.add(Price, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, 100, 30));

        price1.setBackground(new java.awt.Color(255, 204, 153));
        price1.setText("Number");
        jPanel5.add(price1, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 130, 130, 30));

        Category.setBackground(new java.awt.Color(255, 204, 153));
        Category.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Clothes", "Food", "Books", " ", " " }));
        Category.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CategoryActionPerformed(evt);
            }
        });
        jPanel5.add(Category, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 90, -1, -1));

        Name3.setFont(new java.awt.Font("Agency FB", 0, 24)); // NOI18N
        Name3.setForeground(new java.awt.Color(255, 255, 255));
        Name3.setText("Item Name :");
        jPanel5.add(Name3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, 120, 30));

        Name.setBackground(new java.awt.Color(255, 204, 153));
        Name.setText("Number");
        jPanel5.add(Name, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 30, 130, 30));

        Name4.setFont(new java.awt.Font("Agency FB", 0, 24)); // NOI18N
        Name4.setForeground(new java.awt.Color(255, 255, 255));
        Name4.setText("Price :");
        jPanel5.add(Name4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 130, 120, 30));

        Desc.setBackground(new java.awt.Color(255, 204, 153));
        Desc.setColumns(20);
        Desc.setRows(5);
        jScrollPane1.setViewportView(Desc);

        jPanel5.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 280, 170, 170));

        Name5.setFont(new java.awt.Font("Agency FB", 0, 24)); // NOI18N
        Name5.setForeground(new java.awt.Color(255, 255, 255));
        Name5.setText("Description :");
        jPanel5.add(Name5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 280, 120, 30));

        jButton6.setBackground(new java.awt.Color(255, 204, 153));
        jButton6.setFont(new java.awt.Font("Agency FB", 0, 18)); // NOI18N
        jButton6.setText("Save");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        jPanel5.add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 490, 120, 40));

        Name6.setFont(new java.awt.Font("Agency FB", 0, 24)); // NOI18N
        Name6.setForeground(new java.awt.Color(255, 255, 255));
        Name6.setText("Quantity :");
        jPanel5.add(Name6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 180, 120, 30));

        quantity.setBackground(new java.awt.Color(255, 204, 153));
        quantity.setText("Number");
        jPanel5.add(quantity, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 180, 130, 30));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, 423, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, 545, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void uploadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_uploadActionPerformed
        // TODO add your handling code here:
        if(evt.getSource() == upload) {
            JFileChooser open = new JFileChooser();
            open.showOpenDialog(null);
            File file = open.getSelectedFile();    
            String Name ; 
            Name = file.getName() ;
            i.name="image1";
            i.url=Name;
        }
    }//GEN-LAST:event_uploadActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
         Item it = new Item();
        it.Name=Name.getText();
        it.Descritption = Desc.getText();
        it.Quantity = Integer.parseInt( quantity.getText());
       
        

           if( it.AddItem(connection, i, it, select)!=-1)
           {
               this.dispose();
           }
        
        


    }//GEN-LAST:event_jButton6ActionPerformed

    private void CategoryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CategoryActionPerformed
        // TODO add your handling code here:
        JComboBox box= (JComboBox) evt.getSource();
         select = box.getSelectedIndex() +1;
    }//GEN-LAST:event_CategoryActionPerformed

  

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> Category;
    private javax.swing.JTextArea Desc;
    private javax.swing.JTextField Name;
    private javax.swing.JLabel Name2;
    private javax.swing.JLabel Name3;
    private javax.swing.JLabel Name4;
    private javax.swing.JLabel Name5;
    private javax.swing.JLabel Name6;
    private javax.swing.JLabel Price;
    private javax.swing.JButton jButton6;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField price1;
    private javax.swing.JTextField quantity;
    private javax.swing.JButton upload;
    // End of variables declaration//GEN-END:variables
}
