/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Admin;

import core.Admin;
import core.ConnectDB;

/**
 *
 * @author Ansam
 */
public class AddShipping extends javax.swing.JFrame {

    /**
     * Creates new form AddShipping
     */
     ConnectDB connection;
    public AddShipping( ConnectDB con) {
        initComponents();
        connection=con;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel5 = new javax.swing.JPanel();
        Name2 = new javax.swing.JLabel();
        jButton5 = new javax.swing.JButton();
        Price = new javax.swing.JLabel();
        tyoe = new javax.swing.JTextField();
        fees = new javax.swing.JTextField();
        Price1 = new javax.swing.JLabel();
        duration = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);

        jPanel5.setBackground(new java.awt.Color(0, 51, 102));
        jPanel5.setForeground(new java.awt.Color(255, 255, 255));
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Name2.setFont(new java.awt.Font("Agency FB", 0, 24)); // NOI18N
        Name2.setForeground(new java.awt.Color(255, 255, 255));
        Name2.setText("Shipping method name :");
        jPanel5.add(Name2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, 190, 30));

        jButton5.setBackground(new java.awt.Color(255, 204, 153));
        jButton5.setFont(new java.awt.Font("Agency FB", 0, 18)); // NOI18N
        jButton5.setText("Save");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jPanel5.add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 210, 120, 40));

        Price.setFont(new java.awt.Font("Agency FB", 0, 24)); // NOI18N
        Price.setForeground(new java.awt.Color(255, 255, 255));
        Price.setText("Fees:");
        jPanel5.add(Price, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 130, 100, 30));

        tyoe.setBackground(new java.awt.Color(255, 204, 153));
        tyoe.setText("name");
        jPanel5.add(tyoe, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 30, 130, 30));

        fees.setBackground(new java.awt.Color(255, 204, 153));
        fees.setText("fees");
        fees.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                feesActionPerformed(evt);
            }
        });
        jPanel5.add(fees, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 130, 130, 30));

        Price1.setFont(new java.awt.Font("Agency FB", 0, 24)); // NOI18N
        Price1.setForeground(new java.awt.Color(255, 255, 255));
        Price1.setText("Estimated shipping time :");
        jPanel5.add(Price1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, 200, 30));

        duration.setBackground(new java.awt.Color(255, 204, 153));
        duration.setText("Time");
        duration.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                durationActionPerformed(evt);
            }
        });
        jPanel5.add(duration, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 80, 130, 30));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, 432, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, 299, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        String ty=tyoe.getText();
        String Dur=duration.getText();
        String fee=fees.getText();
        Admin a = new Admin();
        a.AddShipping(ty, Dur, Float.parseFloat(fee), connection);
        this.dispose();
    }//GEN-LAST:event_jButton5ActionPerformed

    private void feesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_feesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_feesActionPerformed

    private void durationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_durationActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_durationActionPerformed

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Name2;
    private javax.swing.JLabel Price;
    private javax.swing.JLabel Price1;
    private javax.swing.JTextField duration;
    private javax.swing.JTextField fees;
    private javax.swing.JButton jButton5;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JTextField tyoe;
    // End of variables declaration//GEN-END:variables
}
